-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggefnSQS46EhWuavY
13w9eOZr/lHIe8J6GruzVX9dVfCgCgYIKoZIzj0DAQehRANCAATsPw/HyoxcTJWQ
nbvSBIQfMlKpN6OO3SO7hU80cS2MsxmI2SQQmWvIreakflO+rQYe/md3kYTspEds
ZVcz6pG7
-----END PRIVATE KEY-----